FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["streamlit","run","Home.py","--server.address=0.0.0.0","--server.port=3000"]