version: '3.8'

services:

  backend:
    build: ./backend
    container_name: ai_backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    env_file:
      - .env

    restart: always


  frontend:
    build: ./frontend
    container_name: ai_frontend

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app

    depends_on:
      - backend

    restart: always